// Mutation事件类型
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const RESET_VUEX_STATE = 'RESET_VUEX_STATE';

export const FETCH_CART_LIST_SUCCESS = 'FETCH_CART_LIST_SUCCESS';
export const FETCH_CART_LIST_FAIL = 'FETCH_CART_LIST_FAIL';
export const FETCH_GOODS_LIST_SUCCESS = 'FETCH_GOODS_LIST_SUCCESS';
export const FETCH_GOODS_LIST_FAIL = 'FETCH_GOODS_LIST_FAIL';
export const FETCH_CART_DELETE_SUCCESS = 'FETCH_CART_DELETE_SUCCESS';
export const FETCH_CART_DELETE_FAIL = 'FETCH_CART_DELETE_FAIL';
export const FETCH_TEST_500_SUCCESS = 'FETCH_TEST_500_SUCCESS';
export const FETCH_TEST_500_FAIL = 'FETCH_TEST_500_FAIL';
export const FETCH_TEST_401_SUCCESS = 'FETCH_TEST_401_SUCCESS';
export const FETCH_TEST_401_FAIL = 'FETCH_TEST_401_FAIL';
export const FETCH_TEST_203_SUCCESS = 'FETCH_TEST_203_SUCCESS';
export const FETCH_TEST_203_FAIL = 'FETCH_TEST_203_FAIL';
export const FETCH_USER_LOGOUT_SUCCESS = 'FETCH_USER_LOGOUT_SUCCESS';
export const FETCH_USER_LOGOUT_FAIL = 'FETCH_USER_LOGOUT_FAIL';

export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL';

export const FETCH_CART_ADD_SUCCESS = 'FETCH_CART_ADD_SUCCESS';
export const FETCH_CART_ADD_FAIL = 'FETCH_CART_ADD_FAIL';
